language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.2

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luaunit
  - luarocks install penlight
  - luarocks install luacov-coveralls

script: lua  -lluacov run_tests.lua

after_success: luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
